import {
  Repository,
  PullRequest,
  AlignmentDocument,
  DashboardStats,
} from "./types";

export const mockRepositories: Repository[] = [
  {
    id: "1",
    name: "vortex-platform",
    fullName: "acme-corp/vortex-platform",
    description: "Main platform codebase for the Vortex PR review system",
    language: "TypeScript",
    stars: 128,
    forks: 24,
    openPRs: 5,
    lastUpdated: "2025-01-15T10:30:00Z",
    isPrivate: true,
    defaultBranch: "main",
    url: "https://github.com/acme-corp/vortex-platform",
  },
  {
    id: "2",
    name: "api-gateway",
    fullName: "acme-corp/api-gateway",
    description: "API Gateway service handling authentication and routing",
    language: "Go",
    stars: 89,
    forks: 12,
    openPRs: 3,
    lastUpdated: "2025-01-14T15:45:00Z",
    isPrivate: true,
    defaultBranch: "main",
    url: "https://github.com/acme-corp/api-gateway",
  },
  {
    id: "3",
    name: "design-system",
    fullName: "acme-corp/design-system",
    description: "Shared component library and design tokens",
    language: "TypeScript",
    stars: 256,
    forks: 45,
    openPRs: 8,
    lastUpdated: "2025-01-15T08:20:00Z",
    isPrivate: false,
    defaultBranch: "main",
    url: "https://github.com/acme-corp/design-system",
  },
  {
    id: "4",
    name: "ml-pipeline",
    fullName: "acme-corp/ml-pipeline",
    description: "Machine learning data processing and model training pipeline",
    language: "Python",
    stars: 67,
    forks: 8,
    openPRs: 2,
    lastUpdated: "2025-01-13T22:10:00Z",
    isPrivate: true,
    defaultBranch: "develop",
    url: "https://github.com/acme-corp/ml-pipeline",
  },
  {
    id: "5",
    name: "mobile-app",
    fullName: "acme-corp/mobile-app",
    description: "React Native mobile application for iOS and Android",
    language: "TypeScript",
    stars: 34,
    forks: 5,
    openPRs: 4,
    lastUpdated: "2025-01-15T12:00:00Z",
    isPrivate: true,
    defaultBranch: "main",
    url: "https://github.com/acme-corp/mobile-app",
  },
  {
    id: "6",
    name: "infra-config",
    fullName: "acme-corp/infra-config",
    description: "Infrastructure as code - Terraform and Kubernetes configs",
    language: "HCL",
    stars: 15,
    forks: 3,
    openPRs: 1,
    lastUpdated: "2025-01-12T09:30:00Z",
    isPrivate: true,
    defaultBranch: "main",
    url: "https://github.com/acme-corp/infra-config",
  },
];

export const mockPullRequests: PullRequest[] = [
  {
    id: "1",
    number: 342,
    title: "feat: Add user authentication middleware",
    description:
      "Implements JWT-based authentication middleware with refresh token rotation. This includes rate limiting and session management.",
    state: "open",
    author: {
      name: "Sarah Chen",
      avatar: "",
      username: "sarahchen",
    },
    repository: "acme-corp/api-gateway",
    sourceBranch: "feat/auth-middleware",
    targetBranch: "main",
    createdAt: "2025-01-15T09:00:00Z",
    updatedAt: "2025-01-15T14:30:00Z",
    additions: 847,
    deletions: 123,
    changedFiles: 12,
    labels: ["feature", "security"],
    reviewStatus: "pending",
  },
  {
    id: "2",
    number: 189,
    title: "fix: Resolve memory leak in WebSocket handler",
    description:
      "Fixed a memory leak caused by unclosed event listeners in the WebSocket connection handler. Added proper cleanup on disconnect.",
    state: "open",
    author: {
      name: "Marcus Johnson",
      avatar: "",
      username: "marcusj",
    },
    repository: "acme-corp/vortex-platform",
    sourceBranch: "fix/ws-memory-leak",
    targetBranch: "main",
    createdAt: "2025-01-14T16:20:00Z",
    updatedAt: "2025-01-15T10:15:00Z",
    additions: 56,
    deletions: 34,
    changedFiles: 3,
    labels: ["bug", "performance"],
    reviewStatus: "reviewed",
    aiReview: {
      id: "r1",
      summary:
        "Good fix for the memory leak. The cleanup logic is well-structured. Minor suggestion: consider adding a connection timeout as an additional safeguard.",
      score: 88,
      issues: [
        {
          severity: "info",
          title: "Consider adding connection timeout",
          description:
            "While the fix addresses the immediate leak, adding a connection timeout would prevent zombie connections.",
          file: "src/handlers/websocket.ts",
          line: 45,
        },
      ],
      suggestions: [
        {
          title: "Add timeout configuration",
          description: "Make the connection timeout configurable via environment variables",
          file: "src/config/websocket.ts",
          code: "const WS_TIMEOUT = process.env.WS_TIMEOUT || 30000;",
        },
      ],
      alignmentChecks: [
        { rule: "Error handling standards", status: "pass", description: "Proper error handling with try-catch blocks" },
        { rule: "Code documentation", status: "pass", description: "Functions are properly documented" },
        { rule: "Test coverage", status: "warning", description: "Test coverage at 72% - target is 80%" },
      ],
      generatedAt: "2025-01-15T10:15:00Z",
    },
  },
  {
    id: "3",
    number: 567,
    title: "refactor: Migrate Button component to new design tokens",
    description:
      "Migrates the Button component to use the new design token system. Updates all variants and adds new size options.",
    state: "open",
    author: {
      name: "Alex Rivera",
      avatar: "",
      username: "alexr",
    },
    repository: "acme-corp/design-system",
    sourceBranch: "refactor/button-tokens",
    targetBranch: "main",
    createdAt: "2025-01-15T11:00:00Z",
    updatedAt: "2025-01-15T13:45:00Z",
    additions: 234,
    deletions: 189,
    changedFiles: 8,
    labels: ["refactor", "design-system"],
    reviewStatus: "pending",
  },
  {
    id: "4",
    number: 78,
    title: "feat: Implement data preprocessing pipeline",
    description:
      "Adds a new data preprocessing pipeline for model training. Includes data validation, normalization, and feature extraction steps.",
    state: "open",
    author: {
      name: "Priya Patel",
      avatar: "",
      username: "priyap",
    },
    repository: "acme-corp/ml-pipeline",
    sourceBranch: "feat/preprocessing",
    targetBranch: "develop",
    createdAt: "2025-01-13T14:00:00Z",
    updatedAt: "2025-01-14T18:30:00Z",
    additions: 1245,
    deletions: 67,
    changedFiles: 15,
    labels: ["feature", "ml"],
    reviewStatus: "approved",
    aiReview: {
      id: "r2",
      summary:
        "Comprehensive preprocessing pipeline with solid architecture. The modular design allows for easy extension. All alignment standards are met.",
      score: 94,
      issues: [],
      suggestions: [
        {
          title: "Consider parallel processing",
          description: "Large datasets could benefit from parallel processing using multiprocessing",
          file: "src/pipeline/preprocessor.py",
          code: "from multiprocessing import Pool",
        },
      ],
      alignmentChecks: [
        { rule: "Code documentation", status: "pass", description: "All modules properly documented" },
        { rule: "Test coverage", status: "pass", description: "Test coverage at 91%" },
        { rule: "Error handling standards", status: "pass", description: "Comprehensive error handling" },
        { rule: "Performance standards", status: "pass", description: "Meets processing time requirements" },
      ],
      generatedAt: "2025-01-14T18:30:00Z",
      publishedAt: "2025-01-14T18:35:00Z",
    },
  },
  {
    id: "5",
    number: 456,
    title: "feat: Add push notification support",
    description:
      "Implements push notifications for iOS and Android using Firebase Cloud Messaging. Includes notification preferences and scheduling.",
    state: "open",
    author: {
      name: "Jordan Kim",
      avatar: "",
      username: "jordank",
    },
    repository: "acme-corp/mobile-app",
    sourceBranch: "feat/push-notifications",
    targetBranch: "main",
    createdAt: "2025-01-14T10:00:00Z",
    updatedAt: "2025-01-15T09:00:00Z",
    additions: 678,
    deletions: 45,
    changedFiles: 18,
    labels: ["feature", "mobile"],
    reviewStatus: "changes_requested",
    aiReview: {
      id: "r3",
      summary:
        "The notification implementation is functional but has security concerns with token storage and missing error handling in critical paths.",
      score: 62,
      issues: [
        {
          severity: "critical",
          title: "FCM token stored in plain text",
          description: "The Firebase Cloud Messaging token is stored in AsyncStorage without encryption. Use SecureStore instead.",
          file: "src/services/notifications.ts",
          line: 23,
        },
        {
          severity: "warning",
          title: "Missing error boundary in notification handler",
          description: "The notification handler lacks error boundaries which could cause the app to crash on malformed payloads.",
          file: "src/handlers/notification.ts",
          line: 67,
        },
        {
          severity: "info",
          title: "Consider notification grouping",
          description: "For better UX, consider implementing notification grouping for Android 7.0+.",
        },
      ],
      suggestions: [
        {
          title: "Use SecureStore for token storage",
          description: "Replace AsyncStorage with expo-secure-store for sensitive data",
          file: "src/services/notifications.ts",
          code: "import * as SecureStore from 'expo-secure-store';",
        },
      ],
      alignmentChecks: [
        { rule: "Security standards", status: "fail", description: "Sensitive data stored without encryption" },
        { rule: "Error handling standards", status: "fail", description: "Missing error handling in critical paths" },
        { rule: "Code documentation", status: "pass", description: "Well-documented implementation" },
        { rule: "Test coverage", status: "warning", description: "Test coverage at 65% - target is 80%" },
      ],
      generatedAt: "2025-01-15T09:00:00Z",
    },
  },
  {
    id: "6",
    number: 23,
    title: "chore: Update Terraform provider versions",
    description:
      "Updates all Terraform provider versions to latest stable releases. Includes migration notes for breaking changes.",
    state: "merged",
    author: {
      name: "Chris Taylor",
      avatar: "",
      username: "christaylor",
    },
    repository: "acme-corp/infra-config",
    sourceBranch: "chore/update-providers",
    targetBranch: "main",
    createdAt: "2025-01-12T08:00:00Z",
    updatedAt: "2025-01-12T14:00:00Z",
    additions: 89,
    deletions: 76,
    changedFiles: 5,
    labels: ["chore", "infrastructure"],
    reviewStatus: "approved",
    aiReview: {
      id: "r4",
      summary: "Clean provider version updates with proper migration handling. All changes are well-documented.",
      score: 96,
      issues: [],
      suggestions: [],
      alignmentChecks: [
        { rule: "Infrastructure change documentation", status: "pass", description: "All changes documented with migration notes" },
        { rule: "Version pinning", status: "pass", description: "All providers pinned to specific versions" },
      ],
      generatedAt: "2025-01-12T10:00:00Z",
      publishedAt: "2025-01-12T10:05:00Z",
    },
  },
];

export const mockAlignmentDocuments: AlignmentDocument[] = [
  {
    id: "1",
    name: "Code Quality Standards",
    fileName: "code-quality-standards-v2.pdf",
    fileSize: 2450000,
    uploadedAt: "2025-01-10T09:00:00Z",
    status: "ready",
    rulesExtracted: 47,
    description: "Organization-wide code quality standards including naming conventions, error handling, and documentation requirements.",
  },
  {
    id: "2",
    name: "Security Guidelines",
    fileName: "security-guidelines-2025.pdf",
    fileSize: 3200000,
    uploadedAt: "2025-01-08T14:30:00Z",
    status: "ready",
    rulesExtracted: 32,
    description: "Security best practices and requirements for all development projects including authentication, data handling, and encryption.",
  },
  {
    id: "3",
    name: "API Design Principles",
    fileName: "api-design-principles.pdf",
    fileSize: 1800000,
    uploadedAt: "2025-01-12T11:00:00Z",
    status: "ready",
    rulesExtracted: 28,
    description: "REST and GraphQL API design standards, versioning policies, and error response formats.",
  },
  {
    id: "4",
    name: "Testing Strategy Document",
    fileName: "testing-strategy-2025.pdf",
    fileSize: 4100000,
    uploadedAt: "2025-01-15T08:00:00Z",
    status: "processing",
    rulesExtracted: 0,
    description: "Comprehensive testing strategy including unit, integration, and e2e testing requirements and coverage targets.",
  },
];

export const mockDashboardStats: DashboardStats = {
  totalReviews: 156,
  totalPRs: 234,
  averageScore: 82,
  alignmentRate: 91,
  reviewsThisWeek: 23,
  issuesFound: 47,
};

export const mockActivityFeed = [
  { id: "1", type: "review" as const, message: "AI review completed for PR #342", repo: "api-gateway", time: "2 min ago", score: 88 },
  { id: "2", type: "publish" as const, message: "Review published for PR #78", repo: "ml-pipeline", time: "15 min ago" },
  { id: "3", type: "upload" as const, message: "New alignment document uploaded", repo: "", time: "1 hour ago" },
  { id: "4", type: "review" as const, message: "AI review completed for PR #456", repo: "mobile-app", time: "2 hours ago", score: 62 },
  { id: "5", type: "merge" as const, message: "PR #23 merged after review", repo: "infra-config", time: "3 hours ago" },
  { id: "6", type: "review" as const, message: "AI review completed for PR #189", repo: "vortex-platform", time: "5 hours ago", score: 94 },
];

export const mockWeeklyActivity = [
  { day: "Mon", reviews: 8, prsOpened: 5, issuesFound: 3 },
  { day: "Tue", reviews: 12, prsOpened: 7, issuesFound: 5 },
  { day: "Wed", reviews: 6, prsOpened: 4, issuesFound: 2 },
  { day: "Thu", reviews: 15, prsOpened: 9, issuesFound: 7 },
  { day: "Fri", reviews: 10, prsOpened: 6, issuesFound: 4 },
  { day: "Sat", reviews: 3, prsOpened: 2, issuesFound: 1 },
  { day: "Sun", reviews: 2, prsOpened: 1, issuesFound: 0 },
];

export const mockReviewsByRepo = [
  { repo: "vortex-platform", reviews: 42, avgScore: 85 },
  { repo: "api-gateway", reviews: 28, avgScore: 79 },
  { repo: "design-system", reviews: 35, avgScore: 91 },
  { repo: "ml-pipeline", reviews: 18, avgScore: 88 },
  { repo: "mobile-app", reviews: 22, avgScore: 72 },
  { repo: "infra-config", reviews: 11, avgScore: 94 },
];

export const mockPRStatusDistribution = [
  { name: "Merged", count: 89, fill: "#8b5cf6" },
  { name: "Open", count: 23, fill: "#6366f1" },
  { name: "Pending Review", count: 15, fill: "#a78bfa" },
  { name: "Changes Requested", count: 8, fill: "#4f46e5" },
];

export const mockScoreDistribution = [
  { range: "90-100", count: 42, fill: "#22c55e" },
  { range: "80-89", count: 38, fill: "#8b5cf6" },
  { range: "70-79", count: 25, fill: "#6366f1" },
  { range: "60-69", count: 12, fill: "#eab308" },
  { range: "< 60", count: 5, fill: "#ef4444" },
];
